name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        export POETRY_HOME=/opt/poetry
        python3 -m venv $POETRY_HOME
        $POETRY_HOME/bin/pip install poetry==1.4.2
        $POETRY_HOME/bin/poetry --version
        $POETRY_HOME/bin/poetry install
    - name: Run Tests
      run: |
        poetry run python manage.py test
